spring:
  profiles:
    active: development

---

spring:
  profiles: development
  data:
    rest:
      base-path: /catalog-service
    mongodb:
      host: localhost
      port: 27017
      database: catalog
      repositories:
        enabled: true
# HTTP Server
server:
  port: ${PORT:3333}   # HTTP (Tomcat) port

management:
  security:
    enabled: false

---

spring:
  profiles: cloud
  data:
    rest:
      base-path: /
    mongodb:
      host: ${MICROXS_COMMERCE_MONGO_SERVICE_HOST}
      port: ${MICROXS_COMMERCE_MONGO_SERVICE_PORT}
      database: catalog
      repositories:
        enabled: true
# HTTP Server
server:
  port: ${PORT:3333}   # HTTP (Tomcat) port

management:
  security:
    enabled: true
